keys:
  - &framework age1ndchua47ezajw5nk8yj6vhmgkxn05lke33s0g48kgf58yapxz3gqguk23j
  - &homelab2 age1ky8phu7rmf6yashsrp25ep22yc4nulm7eakss2l764rhf0m4r3tqm0jgz8
  - &homelab3 age1can73zkeq8v9r4a8egrmrnx753jdd2fss9l08jmc8pvh3jyptf2spz20nu
  - &stronghold age1966dt3tnupyte5aw7nggn8cmp2uh498nyjgv08tnxfdc8ur884ysnnq34s
  - &t14s age1tjd9fn32wuykv83zejgjw4azqtetw5lzqae602hcgmgmzsagg37q2d7ka5
  - &p14s age17r4q9qnwuyu6ehd55an757a9nhnd7pqnt9a6fctl7rd6m3lj2cgqjtqtgx

creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
          - *framework
          - *homelab2
          - *homelab3
          - *stronghold
          - *t14s
          - *p14s
