keys:
  - &primary age1ggewvthjqlw00k678ler222pp6tqmgrtzdpa5l2lua3dvkyk493q5mj7ge
  - &ci age1yy3st8hmrlz2h4nmu4nuqns9y8heq6ge8ug8d8pwaajdg66hyetq4z0w8j
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
          - *primary
          - *ci
