name: automerge
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@7961b8b5eec56cc088c140b56d864285eabd3f67" # v0.16.4
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
          UPDATE_METHOD: "rebase"
