# Source: https://github.com/tlvince/nixos-config/blob/master/.github/workflows/build.yml
name: Build
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  build:
    env:
      PR_JOB_SUMMARY: pr-job-summary
      NIX_GITHUB_PRIVATE_USERNAME:
      NIX_GITHUB_PRIVATE_PASSWORD:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    strategy:
      matrix:
        host:
          - p14s
          - t14s
          - homelab2
      fail-fast: false
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.host }}
      cancel-in-progress: true
    steps:
      - name: Free up disk space
        uses: AdityaGarg8/remove-unwanted-software@90e01b21170618765a73370fcc3abbd1684a7793
        with:
          remove-android: true
          remove-cached-tools: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true
          remove-large-packages: true
          remove-swapfile: true
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20
      - name: Setup Attic cache
        uses: ryanccn/attic-action@7fbafba3978e86e585cb68a82c08b30f3672b62d # v0
        with:
          endpoint: https://attic.terence.cloud
          cache: homelab
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Build
        run: |
          sudo systemctl set-environment NIX_GITHUB_PRIVATE_USERNAME=${{ github.repository_owner }}
          sudo systemctl set-environment NIX_GITHUB_PRIVATE_PASSWORD=${{ secrets.GH_TOKEN_FOR_UPDATES }}
          sudo systemctl daemon-reload && sudo systemctl restart nix-daemon
          OUT_PATH="$(nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --print-out-paths --access-tokens github.com=${{ secrets.GH_TOKEN_FOR_UPDATES }})"
          echo -e "\x1b[32;1mSuccessfully built .#nixosConfigurations.${{ matrix.host }}\x1b[0m"
          echo -e "## Build ${{ matrix.host }}\n\`$OUT_PATH\`" | tee -a "$GITHUB_STEP_SUMMARY" "${RUNNER_TEMP}/${PR_JOB_SUMMARY}" >/dev/null
      - name: Diff closures
        if: github.event_name == 'pull_request'
        run: |
          sudo systemctl set-environment NIX_GITHUB_PRIVATE_USERNAME=${{ github.repository_owner }}
          sudo systemctl set-environment NIX_GITHUB_PRIVATE_PASSWORD=${{ secrets.GH_TOKEN_FOR_UPDATES }}
          sudo systemctl daemon-reload && sudo systemctl restart nix-daemon
          HOST_DRV="nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel"
          PREV_FLAKE="github:${GITHUB_REPOSITORY}"
          NEXT_FLAKE="."
          DIFF_OUTPUT="${RUNNER_TEMP}/nix-store-diff-closures-output"
          nix store diff-closures "${PREV_FLAKE}#${HOST_DRV}" "${NEXT_FLAKE}#${HOST_DRV}" --access-tokens github.com=${{ secrets.GH_TOKEN_FOR_UPDATES }} --no-write-lock-file | tee "$DIFF_OUTPUT"
          [[ -s "$DIFF_OUTPUT" ]] && sed -i 's/\x1b\[[0-9;]*m//g' "$DIFF_OUTPUT" || echo "No changes found" | tee "$DIFF_OUTPUT"
          echo -e "## Closures difference\n\`\`\`\n$(<$DIFF_OUTPUT)\n\`\`\`" | tee -a "$GITHUB_STEP_SUMMARY" "${RUNNER_TEMP}/${PR_JOB_SUMMARY}" >/dev/null
      - name: Add job summary to PR
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        if: github.event_name == 'pull_request'
        with:
          script: |
            const { readFile } = require('node:fs/promises')
            const comment = require('.github/scripts/comment')
            const header = '# ${{ matrix.host }}'
            const body = await readFile('${{ runner.temp }}/${{ env.PR_JOB_SUMMARY }}', { encoding: 'utf8' })
            await comment({ github, context, header, body })
