nixos-access-tokens: ENC[AES256_GCM,data:VpvKl986yh+GvjHsZ+zJe99HwWSKL591qRgBPelKcHGGpaDHe0QhoTv0xzBlqtLCiU5tjSUw1Gwegl9SoW1JSArZMA==,iv:tWllyZLMmB1Kj8jJFQcfboRYDwekKVt34K9BZd63AFw=,tag:4v5MbLUkRPLCDmOabXDsXg==,type:str]
nix-daemon-environment: ENC[AES256_GCM,data:XI/zNbbgTGh76u2VJa9ddbYAOzwow83K+78/nKTCQ7AHorljLosBzwe8tgtWOYo0+2vKRAXIW5A6wLu5PV9ZmEktqHbxOMRlZKdglRDuW19ByNAQ97ZCI8uwRdNvsahJke5S2EKPXIP3eg==,iv:wjFTA/96xc3wdyIEoaIcYr/X+mwbbhJBn+2RiDaTbqs=,tag:bJeD66aOHveSisPPHWwIvw==,type:str]
sops:
    age:
        - recipient: age1dz90388umnh8nmk2akt89le408t7488ruax60zdww2lhgvasrp0q5tlal8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT0JEVlBwQ3VjYVIyeXJQ
            elJ5SGdyNEZFbWRvVjlFeTBXY0E3WHJ2RlRFClc2c2NRY2xZd2J4TVAwV2xPQWF4
            bGYyM1lNa1VFZjNIRmJEZSttd2lmOFUKLS0tIEI5YkZuWG5GS0hPK09jSUxobzJ5
            amNxb2pzcVZaQWppZmJ6cm00TFJKNEkKLNyUaCFDqLD+47Zh1BgOKsgqxSWHtRCn
            xvCW9UKNWeqDon17Xtf1nF14yJrzPOjjeICw58wT0WO9BNf7dZFrSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16h63pg8r7xfzu4shptpchztgnw5q3t3s08x5fvclmq9hya94zvwqfkwxv6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U1dGSDVlZ0xrVDh2Mjcr
            TDU4TnBSdmMrSHZvbGNwc1JEbHFWYTdYUlJRCktZYlpHcjJvbTlyZXZJditCWURX
            ZjBISGwybGdoYjEyQkxCRXBQZzRGTDgKLS0tIGRjUGJ3NXdyd0RIc3JwTXpTbmpS
            SC9RODgrbE0yQUROTkswaEJyY1FLcnMKthDIxUojpRy30AyGAK8m4cQUcMhZX03t
            peV/GSPipBsfufYkD07WEtUSj+CfjpwROt6S795eTA3lMIBZ76FpqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:46:31Z"
    mac: ENC[AES256_GCM,data:1Zf6MeuOATycvBXBOoP/D7bDqEWU7LaWXfndHUaKNPJmpw9nOLCJPZYk+DCD7jfuljio6ZrSshr/UtwZRvIq2O9kkBc31aSOYkJ04s0Vu7aT5P5JNK1m4xn6tSiuSZ2f2BgxdCGiyN6S8QcYrmsnMpYgQAaOQGdlaMDfdNFK2/o=,iv:ZPY43Yxewzy/9T+O6Hm0mc4FQXQIcmkB+tBlAytNnBg=,tag:l4P+sdyi6+Fs6/4mkm3b1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
