nixos-access-tokens: ENC[AES256_GCM,data:5S7PfywJ3/XKP+XBnBFhN6CzyxKtiTDjYYvllSk8HighSliU1MgJlSqEvrxdjyYEH7bC6JLz/sNpQd/SeMn0hSgWTnc=,iv:R3QgsAOcT/jTa4JE1zKPFExKaItMZoT3MgRbrYbgldM=,tag:OA3Qx1sedBOT1uEFWL+6Yg==,type:str]
nix-daemon-environment: ENC[AES256_GCM,data:XI/zNbbgTGh76u2VJa9ddbYAOzwow83K+78/nKTCQ7AHorljLosBzwe8tgtWOYo0+2vKRAXIW5A6wLu5PV9ZmEktqHbxOMRlZKdglRDuW19ByNAQ97ZCI8uwRdNvsahJke5S2EKPXIP3eg==,iv:wjFTA/96xc3wdyIEoaIcYr/X+mwbbhJBn+2RiDaTbqs=,tag:bJeD66aOHveSisPPHWwIvw==,type:str]
sops:
    age:
        - recipient: age1dz90388umnh8nmk2akt89le408t7488ruax60zdww2lhgvasrp0q5tlal8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcXVuQkloTVF5bXZjQk12
            OVIyTFRVQ1RMWVZxMXRvOWpjcDBtcmNDTGlVClY2RXpNM3FZb2NqWVZqdCtkazlZ
            UnJrSVBPZjA2OFdRRlBKT2lkZHYwWU0KLS0tIE9GZzNPeG9BSDQrVW0xUTROTnRK
            M0E5RUY2bTI0UmY3SkRhN3c2VENHRlEK48prcr1A4P1Sfl9pVNZUNJ33toFf1/sE
            gKG1BIbUGaFHenj2OvtFs0jpwQMbCrWIgSf7PFRGIYwqbx/F2lmCUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16h63pg8r7xfzu4shptpchztgnw5q3t3s08x5fvclmq9hya94zvwqfkwxv6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZlVtNXdZbnkzZFVrOTJh
            a2lGQnJLdzZxUUdEYnNvSHFTYmlUa2ZOQ2s0CmdPWSt1STVFajAxOW9ocnZ2SEhq
            SVhUWFlRbWw0aXI1SU9sVWJTajlzdFUKLS0tIGJxdGtVR2lXK0IweHZsMyt6NUk2
            SjV0Ky9zSDljR2hhTktJMGI4Qi96TVkKAs8imaD5Y1A2jMb3aiXcl4+WuQR8QoCa
            i/BLKb7c18nuTY3rSsY0orjgaaEOBd4ow/tR9QUNLK+Se8mn5ju+jQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ky8phu7rmf6yashsrp25ep22yc4nulm7eakss2l764rhf0m4r3tqm0jgz8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeGtVZFNEZWN4aFhuc1M3
            RjJ6bW81MGxVSGF3eHVDZ1NpOXZZV0t4aGpVCmFxUytFMlZOb1ptdVc4L2ZxeXhK
            bVdwRDlFSmdSaXlNaGN3NlVlOHFuUUEKLS0tIGhHMkY1Q1J5cjVzckM5S3VpK1BS
            QjQwK0s3VzlwcXkxOVpGRXc4dFNSSkUK2Mc9EhitTxjKW+TWvPlhEI+fbYOeHYql
            AdDBd+oyOhUwkzOPCKdLq7rnlwTIlpFnAncWK0ou8bx7/XULLcpcXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1can73zkeq8v9r4a8egrmrnx753jdd2fss9l08jmc8pvh3jyptf2spz20nu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOGtWcTY5dTZVMENyb1Uw
            eHB1WUs2amxjbDBRaFRxR2paWml0VkkrWUhJCkt3akVQQTUrc3k3SFp1SXlWNWdx
            SFdwK1BqZzVwYnArZGxnQlBBNlovV2MKLS0tIEl3M0tQYkYzZlI3SVdLVlg4YVQv
            NXVaY0Z6YjhOd0xlT3llV2dXWHNlcVUK+dGpTXkz6DT2uuG22bTRHeQCz8y1z/0I
            4Fa2o4nqvRDSFDVGVmI2zR2i62XYKbfevmdQGXyvs5qE8Op8VDEBAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1966dt3tnupyte5aw7nggn8cmp2uh498nyjgv08tnxfdc8ur884ysnnq34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRlhQZzFteVVhbVN1cGxR
            aXpkMWJsUEduVEhvZjdjZHVua3JvbU9weWpNCjhXOEIwRDZCdkVRakczRWFSMWs4
            OXhUaHd1K1BVQ2VNYmV5bi9qQ2o3RTgKLS0tIEg4ejVubVJMVW5VWUdyc0U5dklW
            UDk4VlhLeWlzL0N0L0R3eEVzV0lTcUEKTMOCaPVsShqlthxBl0UR2J7e5RKu/VyY
            LQzl9XYV9wGqKshpqCalVSVWCbzDYppYyF+cUsg2thmuazgOVTVAlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tjd9fn32wuykv83zejgjw4azqtetw5lzqae602hcgmgmzsagg37q2d7ka5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcTR2akttbXdmV1VrNnNa
            OHNiaEk1MERzeldlMXBWRExVYmFOVEhMZW53CnIxUENwbGlZY0ZXV2xHWnF0ZUVI
            eG50clRWdm82cm5HUk9SVDJDd1ZxZEEKLS0tIGwvTVFzS2l4MDZWUWZiUDJrcmN2
            Z3hlblBzYUk0aHVqdWVkQzJVK1h3QTAKm19/FcJ02IszUEFb0UzNsewrI9RDpDMM
            8OgIL3lm13hi5qfzRANfL80kVLyu8M5IiTOWPjZMw5uBfoisNNzaNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1efv25tn7w2fcfta2qypx5su5xrscl66h3hau2hv7gxvhchhd9yhsjqnchy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cXo1aFZhcUkvSjRpaVhi
            TnB1ZExOQzJKbXhHcE9ZdEhWUTJTbFlpdmxFCnlxQnVTWERHd0REcW8wRStVM2xo
            V25nRzRKRHl2VTZSTkxaMjh1SGExNk0KLS0tIHc5cTJsM1JmUG9FK1FrN2tJcUJI
            UFlGYW5mR3MyM2t4TlJCb25Nc2xCK3cKJMj8t2NMnwN54Mgq6oTofwniA7djxE7e
            P+BYLtEXrJrlWLFn4cqw6othC+wrhlqTGARGt4bnGmAXj7waAi4B+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ppntenfzfrga9ckpcwcfcp2a3d7l8zshsjhd7m9wpfnrjwq0f5yqtp5sf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySmswaWdyRTV0cFF2c0Q1
            U2VMa3NsQ29YNThKM3lrZjMvNWovNFhiTnlNClRmcHBjaUFzL0N3N1FWdDUwbW5w
            MkFYMTF5OVpMY1Q1NkdzS3VIUzk5NTQKLS0tIENUZzA3bHZKckJoR2tzMS82ekk5
            b3FQVkxpVEhtR1RZZGNUNlZRM29XT2cK0HJiRO/ggmbAsBYoekxUbv2V0XBrY6/0
            vn/qRShcETUFcrxJBCmRr+LhXEnsDNhIxflINhED2hTFb7c8irWgNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1txcs9dqaz9gm2dh49p6tjrxq5tlyez48un5ht5s5yxarkt6agg5sv5cla4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRGw2VTBwYW9NL25qVm5y
            TmNSVUREOXdBa0F4ZlRWWnRabjh1cTd2L1VvCjNyTnI2emZWOFgxdHZ0MHE0UEx4
            bS81VXBOVXdjMVZ5cDYycE83N0V6dEEKLS0tIDNkY0k0c05RUjhSOVBHYk0wRitD
            VUNsdUluVUJLUzJna1lmcklvYW1weVkKKRfjXUdsK1Ssy6aUdTVi/32n2BFZtpqF
            funh9uBYw1KDfyYc5Csw/JEzQg9vEtFBKrJR2c2jjakMFfWwWGjTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T21:06:29Z"
    mac: ENC[AES256_GCM,data:pR7xrklAo4uLm0faNwTvmxUPTNq0S8V8vlp893z4yj1u++HnbdyOuGXdO2Z3yPc9Bqpbj8vdP3xoEKmH7ertO6RIukU6hVKJdOg9smkSFjaWNhwypz1/q4OrcrmVnNCnIb/bc09FYdpNrHNUexs4CFEqFiHw35sAGiZNqmdDt4o=,iv:cvMc85ZVpFdJ6+6XFi9eOdS/66IktzRlYn3nb1ZmCT0=,tag:+oH7rLJ6C2Yz4Tr8xxWYUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
