keys:
  - &primary age1tjd9fn32wuykv83zejgjw4azqtetw5lzqae602hcgmgmzsagg37q2d7ka5
  - &ci age1yy3st8hmrlz2h4nmu4nuqns9y8heq6ge8ug8d8pwaajdg66hyetq4z0w8j
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
          - *primary
          - *ci
